from typing import List, Literal, Optional
from pydantic import BaseModel, Field


class UsageInfo(BaseModel):
    """Token consumption statistics returned by Anthropic."""

    input_tokens: int = Field(
        ..., description="Number of input/prompt tokens processed."
    )
    output_tokens: int = Field(
        ..., description="Number of output tokens generated."
    )


class ChatMessage(BaseModel):
    """Represents a single message turn in the conversation history."""

    role: Literal["user", "assistant"] = Field(
        ..., description="Role of the message sender. Must be 'user' or 'assistant'."
    )
    content: str = Field(..., description="Text content of the message.")


class ChatRequest(BaseModel):
    """Payload for HTTP POST /chat request validation."""

    message: str = Field(
        ..., min_length=1, description="The latest user input message."
    )
    conversation_id: Optional[str] = Field(
        default=None,
        description="Optional unique identifier for multi-turn chat sessions.",
    )
    user_id: Optional[str] = Field(
        default=None,
        description="Optional user identifier for tracing and telemetry.",
    )
    conversation_history: Optional[List[ChatMessage]] = Field(
        default=None,
        description="Optional list of past messages for multi-turn context.",
    )
    system_prompt: Optional[str] = Field(
        default=None, description="Optional system instruction for Claude."
    )
    temperature: float = Field(
        default=0.7,
        ge=0.0,
        le=1.0,
        description="Sampling temperature between 0.0 and 1.0.",
    )
    max_tokens: int = Field(
        default=1000,
        gt=0,
        le=8192,  # Increased from 4096 to support newer high-output models
        description="Maximum tokens to generate (up to 8192).",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "message": "What is my name?",
                "conversation_id": "conv-123",
                "conversation_history": [
                    {"role": "user", "content": "Hi, my name is Alex."},
                    {
                        "role": "assistant",
                        "content": "Hello Alex! How can I assist you today?",
                    },
                ],
                "temperature": 0.7,
                "max_tokens": 1000,
            }
        }
    }


class ChatResponse(BaseModel):
    """Standardized HTTP response wrapper carrying message and execution metadata."""

    message: str = Field(
        ..., description="The textual response generated by Claude."
    )
    model: str = Field(
        default="claude-haiku-4-5-20251001",  # Updated to active model identifier
        description="The specific Anthropic model used for completion.",
    )
    conversation_id: Optional[str] = Field(
        default=None, description="Echoed or session conversation ID."
    )
    usage: Optional[UsageInfo] = Field(
        default=None, description="Token usage statistics for this request."
    )
    stop_reason: Optional[str] = Field(
        default=None,
        description="Reason generation ended (e.g., 'end_turn', 'max_tokens').",
    )